// //////////////////////////////////////////////////////////
// toojpeg.hpp
// written by Stephan Brumme, 2018-2019
// see https://create.stephan-brumme.com/toojpeg/
//
// Fast, lightweight JPEG encoder in C++
// //////////////////////////////////////////////////////////

#pragma once

#include <cstdint>
#include <vector>

namespace TooJpeg {

// Output callback function: called for every byte generated by writeJpeg
typedef void (*WriteByte)(unsigned char oneByte);

// Output bytes to JPEG stream
// - output:      callback for each byte
// - pixels:      raw pixel buffer (RGBRGB... if isRGB=true, else YYY...)
// - width:       image width
// - height:      image height
// - isRGB:       true for 3 channels (RGB), false for 1 channel (Grayscale)
// - quality:     1 (worst) to 100 (best)
// - downsample:  downsample chrominance channels (2x2)
// - comment:     optional JPEG comment
bool writeJpeg(WriteByte output, const void* pixels, unsigned short width, unsigned short height,
               bool isRGB = true, unsigned char quality = 80,
               bool downsample = false, const char* comment = nullptr);

// Convenience wrapper to encode to std::vector<uint8_t>
bool encodeJpeg(const void* pixels, unsigned short width, unsigned short height,
                bool isRGB, unsigned char quality, std::vector<uint8_t>& outputBuffer);

} // namespace TooJpeg
